# Generated by Django 3.1.6 on 2022-08-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
