# Generated by Django 3.1.6 on 2022-08-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
