# Generated by Django 3.1.6 on 2022-08-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='complete',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subjects',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='', max_length=128, null=True),
        ),
    ]
